---
# Default values for http-echo.

## Deployment ressource
replicaCount: 1

image:
  repository: mo3m3n/http-echo
  tag: "latest"
  pullPolicy: IfNotPresent

## Additional labels to add to the pod container metadata
podLabels: {}
#  key: value

## Service Ressource
service:
  type: ClusterIP
  httpPort: 80
  httpsPort: 443

## Ingress ressource
ingress:
  enabled: true
#  host: {{.Release.Name}}.k8s.local
#  defaultBackend: false
  servicePort: http
  annotations: {}
#   kubernetes.io/ingress.class: ""
  tls: {}
#   - secretName: certs/www.kube.dev.h.lo
#     hosts:
#     - www.k8s.local


