{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "http-echo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "http-echo.name" . }}
    helm.sh/chart: {{ include "http-echo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- if not .Values.ingress.defaultBackend }}
  rules:
    - host: {{ include "ingress-host" . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "http-echo.fullname" . }}
              servicePort: {{.Values.ingress.servicePort}}
{{- else }}
            backend:
              serviceName: {{ include "http-echo.fullname" . }}
              servicePort: {{.Values.ingress.servicePort}}
{{- end }}
{{- end }}
